import httpx
from langchain_core.tools import InjectedToolArg, tool
from markdownify import markdownify
from tavily import TavilyClient
from typing_extensions import Annotated, Literal
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
tavily_client = TavilyClient()


@tool(parse_docstring=True)
def tavily_quick_search(
    query: str,
    max_results: int = 5
) -> str:
    """Search the web for a query and return concise summaries/snippets.
    
    This tool does NOT scrape websites. It returns the pre-generated summaries 
    from the search engine, which is much faster and uses fewer tokens.

    Args:
        query: The search query.
        max_results: Number of results to return (default 5).
    """
    # 'search_depth="basic"' is faster and cheaper. 
    # 'include_answer=True' gives a direct answer generated by Tavily.
    response = tavily_client.search(
        query, 
        search_depth="basic", 
        max_results=max_results,
        include_answer=True 
    )

    # 1. Capture the direct answer if available
    output = []
    if response.get("answer"):
        output.append(f"## Direct Answer\n{response['answer']}\n")

    # 2. Format the snippets
    output.append("## Search Results")
    for result in response.get("results", []):
        title = result.get("title", "No Title")
        url = result.get("url", "#")
        # Tavily's 'content' is a high-quality summary of the page
        content = result.get("content", "No content available.")
        
        output.append(f"### [{title}]({url})\n{content}\n")

    return "\n".join(output)

if __name__=="__main__":
    res=tavily_quick_search.invoke("what is philps curve?")
    print(res)

